name: Build and Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./RandomTasks/RandomTasks.csproj

    - name: Build
      run: dotnet build ./RandomTasks/RandomTasks.csproj --configuration Release --no-restore

    - name: Test (Optional)
      run: dotnet test ./RandomTasks/RandomTasks.csproj --no-build --verbosity normal || true

    - name: Publish
      run: dotnet publish ./RandomTasks/RandomTasks.csproj -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: RandomTasks   # This must match your Azure Web App name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
